/**
 * The mirror guard.
 *
 * naming-standards.ts is a hand-written TS port of naming rules whose canonical
 * source is a YAML file in drak-ops (private, Python). Until now the only thing
 * keeping the two in agreement was a comment saying "If the YAML changes,
 * update here too" — an unenforced hand-sync in a package published to npm.
 * Both halves were individually fine and nothing checked the join.
 *
 * These tests assert against the VENDORED copy of the rules
 * (naming_defaults.json, regenerated by scripts/vendor-naming-defaults.sh),
 * and they do it through validateName() rather than by re-reading the module's
 * constants — so they exercise the real code path a caller hits, and cannot
 * pass while the actual validation disagrees with the rules.
 *
 * Coverage note: this closes the join between the vendored copy and the TS.
 * The other join — canonical YAML vs vendored copy — is guarded on the
 * drak-ops side by a checksum test that fails when the YAML changes and tells
 * you to re-run the vendoring script. That tripwire cannot verify this repo
 * was actually updated; it guarantees you are told. Stated here rather than
 * left to look like full coverage.
 */

import { describe, expect, it } from 'vitest';

import rules from './naming_defaults.json';
import { validateName, type EntityType } from './naming-standards.js';

const forbidden = (name: string, entity: EntityType = 'campaign') =>
  validateName(name, entity).filter((v) => v.rule === 'forbidden_chars');

describe('forbidden characters match the vendored rules', () => {
  it.each(rules.forbidden_chars)('rejects %j', (ch) => {
    expect(forbidden(`alpha${ch}beta`)).toHaveLength(1);
  });

  it('rejects no character the rules permit', () => {
    // Shape assertion over the printable-ASCII space, not a handful of
    // examples: catches the TS forbidding MORE than the rules as well as less.
    const probe = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i));
    const rejected = probe.filter((ch) => forbidden(`alpha${ch}beta`).length > 0);
    expect(rejected.sort()).toEqual([...rules.forbidden_chars].sort());
  });
});

describe('allowed pattern matches the vendored rules', () => {
  const canonical = new RegExp(rules.allowed_pattern);

  it.each([
    'simple-name',
    'with_underscore',
    'dotted.name',
    'time:09:00',
    'MixedCase123',
    'has space',
    'has(paren)',
    'emoji-🎯',
  ])('agrees with the canonical regex on %j', (name) => {
    const flagged = validateName(name, 'campaign').some(
      (v) => v.rule === 'allowed_pattern',
    );
    expect(flagged).toBe(!canonical.test(name));
  });
});

describe('length caps match the vendored rules', () => {
  const entities: EntityType[] = ['campaign', 'adgroup', 'ad'];

  it.each(entities)('%s: a name at the cap is accepted', (entity) => {
    const max = rules.length[entity];
    const name = 'a'.repeat(max);
    expect(validateName(name, entity).filter((v) => v.rule === 'length')).toHaveLength(0);
  });

  it.each(entities)('%s: one character over the cap is rejected', (entity) => {
    const max = rules.length[entity];
    const violations = validateName('a'.repeat(max + 1), entity).filter(
      (v) => v.rule === 'length',
    );
    expect(violations).toHaveLength(1);
    expect(violations[0].detail).toContain(String(max));
  });
});

describe('the vendored copy is intact', () => {
  it('records the checksum of the canonical source it came from', () => {
    // The drak-ops-side tripwire quotes this hash when the YAML changes, so a
    // truncated or hand-edited vendor file must not pass silently.
    expect(rules._source_sha256).toMatch(/^[0-9a-f]{64}$/);
  });

  it('carries every rule the TS relies on', () => {
    expect(rules.forbidden_chars.length).toBeGreaterThan(0);
    expect(rules.separator).toBe('-');
    expect(Object.keys(rules.length).sort()).toEqual(['ad', 'adgroup', 'campaign']);
  });
});
